title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: nighthawkcoders/student
github_username: Gavaruba
baseurl: "/Game"
remote_theme: jekyll/minima
minima:
  social_links:
    - {platform: github, user_url: https://github.com/Gavaruba/Game.git}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
